# Generated by Django 5.1.7 on 2025-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_profile_alumniprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='designation',
            field=models.CharField(choices=[('student', 'Student'), ('working', 'Working Professional'), ('teacher', 'Teacher')], default='student', max_length=20),
        ),
    ]
