# Generated by Django 5.1.7 on 2025-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumniprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='current_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
