# Generated by Django 5.1.7 on 2025-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_alumniprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
