# Generated by Django 5.1.7 on 2025-04-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_storycomment_storylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to='alumni.successstory'),
        ),
        migrations.AlterField(
            model_name='storylike',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='alumni.successstory'),
        ),
    ]
