# Generated by Django 5.1.7 on 2025-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_mentorshiprequest_mentee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='success_stories/'),
        ),
    ]
