# Generated by Django 5.1.7 on 2025-04-07 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_successstory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=datetime.date(2025, 4, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='batch_required',
            field=models.CharField(default=datetime.date(2025, 4, 7), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Internship', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='stream',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Electronics', 'Electronics'), ('Engineering any Stream,', 'Engineering any stream'), ('Management', 'Management'), ('Bachelors degree', 'Bachelors degree'), ('Masters', 'Masters'), ('Other', 'Other')], default='Bachelors degree', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
