# Generated by Django 5.1.7 on 2025-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_alter_job_options_remove_job_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_workflow',
            field=models.TextField(default='Interview', help_text='Describe the hiring process steps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='total_openings',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
