# Generated by Django 5.1.7 on 2025-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_remove_job_description_job_apply_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Recruiter_details',
            field=models.TextField(blank=True, help_text='Enter recruiter contact details including phone numbers and additional information', null=True),
        ),
    ]
