# Generated by Django 5.1.7 on 2025-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(help_text="Enter salary (e.g., '50000' or '5 LPA' or 'Not Disclosed')", max_length=50),
        ),
    ]
