# Generated by Django 5.1.7 on 2025-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of attendees allowed'),
        ),
    ]
