# Generated by Django 5.1.7 on 2025-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attendees allowed'),
        ),
    ]
